### ISSUE TITLE
The process was terminated due to an unhandled exception.

### ISSUE THREAD

**Issue by kaichi** [DayZServerApp/DayZServer#5]
Hello,

When I run DayZServer.exe it opens for a few seconds and closes. I took a look at the Event Viewer and found "unhandled exception" error. Please let me know if you need additional details, below are 3 events pertaining to this issue.

===============================

Log Name:      Application
Source:        Application Error
Date:          4/15/2015 8:08:39 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      COMPUTER
Description:
Faulting application name: DayZServer.exe, version: 1.0.0.0, time stamp: 0x552afec1
Faulting module name: KERNELBASE.dll, version: 6.3.9600.17415, time stamp: 0x54504ade
Exception code: 0xe0434352
Fault offset: 0x00014598
Faulting process id: 0x11c8
Faulting application start time: 0x01d0778e0d602d0d
Faulting application path: C:\Users\USERNAME\Desktop\DayZServer\DayZServer.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report Id: 4b3bc77f-e381-11e4-829e-001bdc0fe97f
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-04-15T15:08:39.000000000Z" />
    <EventRecordID>13668</EventRecordID>
    <Channel>Application</Channel>
    <Computer>COMPUTER</Computer>
    <Security />
  </System>
  <EventData>
    <Data>DayZServer.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>552afec1</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.3.9600.17415</Data>
    <Data>54504ade</Data>
    <Data>e0434352</Data>
    <Data>00014598</Data>
    <Data>11c8</Data>
    <Data>01d0778e0d602d0d</Data>
    <Data>C:\Users\USERNAME\Desktop\DayZServer\DayZServer.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\KERNELBASE.dll</Data>
    <Data>4b3bc77f-e381-11e4-829e-001bdc0fe97f</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          4/15/2015 8:08:38 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      COMPUTER
Description:
Application: DayZServer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException
Stack:
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.LoadComponent(System.Uri, Boolean)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Steam.App.Main()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-04-15T15:08:38.000000000Z" />
    <EventRecordID>13667</EventRecordID>
    <Channel>Application</Channel>
    <Computer>COMPUTER</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: DayZServer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException
Stack:
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.LoadComponent(System.Uri, Boolean)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.&lt;.ctor&gt;b__1(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Steam.App.Main()
</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Windows Error Reporting
Date:          4/15/2015 8:08:34 AM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      COMPUTER
Description:
Fault bucket 94719119426, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: DayZServer.exe
P2: 1.0.0.0
P3: 552afec1
P4: DayZServer
P5: 1.0.0.0
P6: 552afec1
P7: 2
P8: 93
P9: System.Windows.Markup.XamlParse
P10: 

Attached files:
C:\Users\USERNAME\AppData\Local\Temp\WER650C.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_DayZServer.exe_1e513ed2daa2ba7f99864fbd3befaeb48c35c_8790230e_0a4465c8

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4827c57a-e381-11e4-829e-001bdc0fe97f
Report Status: 0
Hashed bucket: e45b3d6b43a6598978d1eafe99ccb77a
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-04-15T15:08:34.000000000Z" />
    <EventRecordID>13666</EventRecordID>
    <Channel>Application</Channel>
    <Computer>COMPUTER</Computer>
    <Security />
  </System>
  <EventData>
    <Data>94719119426</Data>
    <Data>5</Data>
    <Data>CLR20r3</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>DayZServer.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>552afec1</Data>
    <Data>DayZServer</Data>
    <Data>1.0.0.0</Data>
    <Data>552afec1</Data>
    <Data>2</Data>
    <Data>93</Data>
    <Data>System.Windows.Markup.XamlParse</Data>
    <Data>
    </Data>
    <Data>
C:\Users\USERNAME\AppData\Local\Temp\WER650C.tmp.WERInternalMetadata.xml</Data>
    <Data>C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_DayZServer.exe_1e513ed2daa2ba7f99864fbd3befaeb48c35c_8790230e_0a4465c8</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>4827c57a-e381-11e4-829e-001bdc0fe97f</Data>
    <Data>0</Data>
    <Data>e45b3d6b43a6598978d1eafe99ccb77a</Data>
  </EventData>
</Event>

**Comment by multimediaxman** [comment]
Thanks for the feedback. There were some dependent files left out of the zip that allow the app to query the DayZ Servers for players.

**Comment by multimediaxman** [comment]
The zip file was missing some dependent files. Thanks for the feedback. The download has been fixed and updated. 

Date: Wed, 15 Apr 2015 08:25:32 -0700
